### ISSUE TITLE
比较好奇为什么没有把工程上传

### ISSUE THREAD

**Issue by zekron** [AtCloudStudio/ShootingStarPackages#1]
我看仓库里已经有代码和部分素材了，为什么不干脆整个工程都上传上来呢？

个人觉得整个工程上传上来方便自己保存项目进度，还可以让社区一起参与开发，也能让懒人（比如我）能直接打包工程到本地自己学习捣鼓。

当然像现在分p上传资源可以让后来的人一步一步跟着开发视频自己制作，这肯定比直接拿到现成的项目学习更有针对性。

**Comment by RYanXuDev** [comment]
没错的，因为这个项目仓库主要是为教程视频服务的，并不是想要和社区一起共同开发，所以我没有把工程文件上传的。
