### ISSUE TITLE
玩家受击后的移动问题

### ISSUE THREAD

**Issue by zekron** [AtCloudStudio/ShootingStarPackages#3]
新版本中（Ep.26）玩家在做出移动输入后静止，并且受到敌人攻击时，玩家会因为`TakeDamage(damage)`方法中`           Move(moveDirection)`导致玩家会按照上次移动输入方向自行移动。

**Comment by RYanXuDev** [comment]
你好，我之前修改这个bug的时候忘记在StopMove()中重置移动方向了 - - 已经在上一期中添加修正了。感谢提醒，抱歉这么久才看到你的评论

**Comment by zekron** [comment]
这里是唧唧，我已经收到你的邮件啦~——来自QQ邮箱的自动回复邮件。
